[package]
name = "design-pattern"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "singleton"
path = "./creational_pattern/singleton_pattern/main.rs"

[[bin]]
name = "factory"
path = "./creational_pattern/factory_method_pattern/main.rs"

[dependencies]
